### ISSUE TITLE
Aimbot problem

### ISSUE THREAD

**Issue by HyronYT1** [xiaofen9/overwatch#10]
Hey i still got the problem with the aimbot. :/ here's a video that shows what i mean. everything is set to default. Sorry for the shitty quality
https://gaming.youtube.com/watch?v=ftosS3QANCc&feature=share

**Comment by xiaofen9** [comment]
seems like the problem of parameter (x,y) in Shoot

**Comment by HyronYT1** [comment]
yeah but how can i fix this?`

**Comment by HyronYT1** [comment]
everything i type in is usless it dosn't change anything

+6

**Comment by xiaofen9** [comment]
set x y to a negative value like -6 -5

**Comment by norlover** [comment]
@HyronYT1  Did you solve the problem? 

I met the same problem as you, modify XY have no effect

**Comment by xiaofen9** [comment]
@norlover In v1.3 it has been solve. Try x,y with bigger value like 10 20

**Comment by norlover** [comment]
Problems still exist @HyronYT1  @xiaofen9
I try to adjust X,Y have no effect.
