### ISSUE TITLE
自瞄出现问题

### ISSUE THREAD

**Issue by Caibiy** [xiaofen9/overwatch#11]
我在训练场的时候自瞄效果还可以，但是实际与玩家操作的时候就会卡而且效果很不好

**Comment by xiaofen9** [comment]
很卡和机器配置有关系 CPU越好 外挂的效果越好 推荐i5 5代 标压以上的cpu

**Comment by Caibiy** [comment]
我是i7 cpu不可能是电脑配置问题，你能不能再出个中文的详细教程

**Comment by norlover** [comment]
貌似游戏更新了 @xiaofen9
