### ISSUE TITLE
Halp !

### ISSUE THREAD

**Issue by japabbu** [xiaofen9/overwatch#14]
When I'm using the overkill my aim starts to shake... D:

**Comment by japabbu** [comment]
Here: https://youtu.be/I-YtZ5kv7Vk *PS: I'm not moving my mouse, just pressing mouse button!

**Comment by xiaofen9** [comment]
read guide over and over. there some parameters remaining to be adjusted

**Comment by japabbu** [comment]
I think that I have done all the things on the guide

**Comment by cristiansc1993** [comment]
All display settings must be set to default, by this I mean, gamma, brightness, etc..
Playing on epic or low shouldnt be the problem.
Run the target program as bordeless windowed.
If after all this you still got problems try on a different computer to see if the problem persist
