### ISSUE TITLE
Still Undetectable? No Ban?

### ISSUE THREAD

**Issue by scanner786** [xiaofen9/overwatch#19]
Hi, i am sorry for the stupid question but there is no other way i can contact you, is this still working and will i get banned for using it?

i just do not wish to try it and get banned unless i am sure it works and wont ban me. I obviously would make it look legit and not abuse it so i get caught, so would that be okay.

Thank You very much and i would like to donate to your work if everything goes well.

**Comment by xiaofen9** [comment]
1. compile it by yourself
2. act, which means you should use it wisely.
