### ISSUE TITLE
使用capslock无法激活脚本（Capslock doesn't work）

### ISSUE THREAD

**Issue by iedc** [xiaofen9/overwatch#21]
使用“无边窗口化”时，设置完参数F2启动之后，在游戏内按Capslock无反应；只有切到桌面按capslock才有反应。这时候脚本不会正常工作。

**Comment by iedc** [comment]
在游戏中无法激活脚本，只能切出去的时候激活，然后就起不到作用。。

**Comment by xiaofen9** [comment]
请仔细阅读英文说明

**Comment by iedc** [comment]
在游戏（已经是无边窗口化）中无法启动，只有切到桌面才能按capslock激活。切回游戏就没有起作用了。
