### ISSUE TITLE
OK 2.0 work only 5 sec 

### ISSUE THREAD

**Issue by Yass37100** [xiaofen9/overwatch#28]
The script work well when i open it and i press F1 while in game, but only for like 5 sec or more... then stop.
and didnt work any more by restarting (F3) and pressing F1 again, or close the ahk completely and opening it again, nothing happened, i have to restart the game if i want to make it work, but again for 5 sec only... how to fix it? please.

**Comment by Crossback** [comment]
how did you get the ahk to open

**Comment by iWonAMathsDebate** [comment]
yea same prob

**Comment by xiaofen9** [comment]
download and install the compile toolkit from https://autohotkey.com
