### ISSUE TITLE
Error when running script.

### ISSUE THREAD

**Issue by scanner786** [xiaofen9/overwatch#30]
Hi, i run the script through autohotkey and it comes up with error saying 

Source: winHttpRequest
description: a connection to the server could not be established. 

This is for the version named overkill. 2.0. 

1.4 works when i load it without errors.

Does anyone know what i should do, or does 1.4 still work ingame?

Thanks.

**Comment by JvlcVictor** [comment]
Got same problem

**Comment by xiaofen9** [comment]
try another version ahk compiler?
