### ISSUE TITLE
Aimbot aims to the right.

### ISSUE THREAD

**Issue by HyronYT1** [xiaofen9/overwatch#4]
The aimbot allways looks to the right. I don't know why everything is setted up like said.

**Comment by xiaofen9** [comment]
set the x in the group box "Shoot" a negative value to solve this problem. Like -2

**Comment by HyronYT1** [comment]
i got the Y now on "5aw"
I don't know why but this only works when i put letters in there too.
but X does not change at all.

**Comment by xiaofen9** [comment]
You can try x+aw and y+aw at the same time for a temp solution. 
I will try to fix it soon.

BTW, what is your system language
