### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by pwallenh** [xiaofen9/overwatch#5]
The Aimbot first wouldnt even work because of line 96. I simply deleted it from the code. The aimbot still isnt working even tho the overlay and everything works

**Comment by xiaofen9** [comment]
1.Script can be complied  with Line 96.  It is not error.
2. What is your graphics card？ IT seems that overkill dont support some AMD yet, due to its terrible color rendering.

**Comment by WhiteShuriken** [comment]
The Aimbot work in AMD, just verify the texture in low

**Comment by xiaofen9** [comment]
texture in low will be addressed in the next readme
