### ISSUE TITLE
ID sealed

### ISSUE THREAD

**Issue by Mrlie** [xiaofen9/overwatch#8]
today ,id was sealed.😫

**Comment by helvet** [comment]
Hi. Can you tell me how did you use this script? Did you just create a .ahk file and used like that? Or did you compile to an .exe? Being banned is a risk that we take when we decide to use things like this.

**Comment by xiaofen9** [comment]
Any one who compile it and always do hash changing dont experience a ban. 
I am writing a dynamic loader to achieve anti-detection in the next version

**Comment by lpanlab** [comment]
Hi, xiaofen, could you tell me how to conduct the hash changing? Thanks a lot.

**Comment by xiaofen9** [comment]
in the corresponding tread of mpgh, someone has post how to encrtpy the hack. 
And i will update my hack soon,  u can just wait for a while.
